management:
  endpoints:
    web:
      exposure:
        include: beans,metrice,info,health,loggers,readiness
  endpoint:
    loggers:
      enabled=false
    health:
      show-details=always
#server:
#  port: 8443
#  ssl:
#    key-store-password: httpspassword
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: przemo

logging:
  level:
    root: WARN
    com.przemo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
